title: Lim Jia Lok # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2nd year student of Bachelor of Computer Science
  <br><br>
  Graduated with a Diploma in Multimedia, Advertising and Broadcasting, Media 
  from Lim Kok Wing University of Creative Technology
  <br><br>
  <a href="https://github.com/TeradonGenesis/Portfolio">Link to my Portfolio Apps in Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
